# Generated by Django 5.2.1 on 2025-06-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
