# Generated by Django 5.2.1 on 2025-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('US', 'USA'), ('FR', 'France'), ('DE', 'Germany')], default='DE'),
        ),
    ]
